In [1]:
from pathlib import Path
import pandas as pd

TEST_DIR = Path(
    r"C:\Users\IDD23\OneDrive\Desktop\е\end-to-end-project\data\week6_test"
)

TEST_DIR.mkdir(parents=True, exist_ok=True)

OUT_PATH = TEST_DIR / "out_append.csv"

if OUT_PATH.exists():
    OUT_PATH.unlink()

df_test = pd.DataFrame({
    "id": [1, 2],
    "v": [10, 20]
})

df_test.to_csv(
    OUT_PATH,
    mode="a",
    header=False,
    index=False
)

df_test.to_csv(
    OUT_PATH,
    mode="a",
    header=False,
    index=False
)

result_bug = pd.read_csv(
    OUT_PATH,
    names=["id", "v"]
)

print("Строк после двух append-запусков:", len(result_bug))
display(result_bug)

Строк после двух append-запусков: 4

   id   v
0   1  10
1   2  20
2   1  10
3   2  20

In [2]:
OUT_SAFE_PATH = TEST_DIR / "out_safe.csv"

if OUT_SAFE_PATH.exists():
    OUT_SAFE_PATH.unlink()

def safe_write(df, path):
    df.to_csv(
        path,
        mode="w",
        header=True,
        index=False
    )

safe_write(df_test, OUT_SAFE_PATH)
safe_write(df_test, OUT_SAFE_PATH)

result_safe = pd.read_csv(OUT_SAFE_PATH)

print("Строк после двух безопасных запусков:", len(result_safe))
display(result_safe)

Строк после двух безопасных запусков: 2

   id   v
0   1  10
1   2  20